name: Deploy

on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build Project
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run fix
      - run: npm run deploy:src
      - run: npm run deploy:docs
      - run: git config --global user.email "ci@github.com"
      - run: git config --global user.name "CI"
      - run: git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      - run: git add -A -- :!.github/**/*
      - run: git diff
      - run: git commit -m "Build Project"
      - run: git push --force
